[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"


[[redirects]]
  from = "/favicon.ico"
  to = "https://assets.gitee.com/:splat"
  status = 200
  force = true
  headers = {Referer = "https://assets.gitee.com"}
  [redirects.headers]
    Referer = "https://assets.gitee.com/"
    Connection = "keep-alive"