[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

[[headers]]
    for = "/*"
    [headers.values]
      Access-Control-Allow-Origin: *

[[redirects]]
  from = "/api/*"
  to = "https://gitee.com/:splat"
  status = 200
  force = true
  headers = {Referer = "https://gitee.com", Origin = "https://gitee.com", content-type = "text/plain;charset=UTF-8"}

[[redirects]]
  from = "*/favicon.ico"
  to = "https://jclio.top/api/:splat"
  status = 200
  force = true
  headers = {Referer = "https://jclio.top/api", content-type = "text/plain;charset=UTF-8"}
