[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"


[[redirects]]
  from = "https://assets.gitee.com/*"
  to = "https://jclio.top/api/:splat"
  status = 200
  force = true
  headers = {Referer = "https://assets.gitee.com", Origin = "https://assets.gitee.com"}


[[redirects]]
  from = "/api/*"
  to = "https://gitee.com/:splat"
  status = 200
  force = true
  headers = {Referer = "https://gitee.com", Origin = "https://gitee.com", content-type = "application/x-www-form-urlencoded;charset=UTF-8"}


