[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, must-revalidate"

[[redirects]]
  from = "/api/*"
  to = "https://gitee.com/:splat"
  status = 200
  force = true
  headers = {Referer = "https://gitee.com", Origin = "https://gitee.com", Host = "gitee.com"}
  [redirects.headers]
    Referer = "https://gitee.com"
    Origin = "https://gitee.com"
    Host = "gitee.com"
    Connection = "keep-alive"
